language: node_js
node_js:
- "8"
- "10"
branches:
  only:
  - master
cache: npm
script:
- npm test
- npm run docs
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/docs
